export enum ActionType {
  LOGIN = "login",
  LOGOUT = "logout",
  LOAD_PRODUCT = "load_product",
  LOAD_USER = "load_user",
  ORDER = "order",
  UPDATE_ORDER = "update_order",
  UPDATE_USER_ACCOUNT = "update_user_account",
  UPDATE_USER_ORDER = "update_user_order",
  CHECKOUT = "checkout",
  ADD_COMMENT = "add_comment",
  REMOVE_COMMENT = "remove_comment",
  ADMIN_DELETE_PRODUCT = "admin_elete_product",
  ADD_PRODUCT = "add_product",
}
